### ISSUE TITLE
GitHub Link

### ISSUE THREAD

**Issue by Fr0hawk** [AviWind02/Address-Formating-tool#1]
GitHub link at the bottom returns nothing.
![image](https://github.com/AviWind02/Address-Formating-tool/assets/72577251/7eb8135a-6df0-444a-b6df-0c301ed93508)

Suggest puting your link in there for the extra exposure ;-)

**Comment by AviWind02** [comment]
Already Added it 10 min ago. But thank you very much for your shitty response
